=== csterryliu/Legal-Attest-Letter-Generator-TW-Django/lal_web/lal_web/generator/lal_module/dep/reportlab/tools/pythonpoint/pythonpoint.dtd
<!--
    pythonpoint.dtd

    PythonPoint XML DTD, version 0.1k
    Copyright 2001-2002 ReportLab, Inc.
                                          
    This is a draft of the DTD for PythonPoint, a program for creating
    presentation slides based on XML. 

    See http://www.reportlab.com for further information.
                                                             
    Common declaration:

    <?xml version='1.0'?>
    <!DOCTYPE presentation
              PUBLIC "-//ReportLab//DTD PythonPoint XML v0.1k//EN"
              "pythonpoint.dtd">

    Please send bug reports, suggestions, etc. to: info@reportlab.com.
-->
<!-- Entities -->
<!ENTITY % bool "true|false">
<!ENTITY % align.values "left|center|right">
<!ENTITY % effectdimension.values "H|V">
<!ENTITY % effectdirection.values "0|90|180|270">
<!ENTITY % effectmotion.values "I|O">
<!ENTITY % effectname.values "Blinds|Box|Dissolve|Glitter|Split|Wipe">
<!-- Top-Level Element -->
<!ELEMENT presentation (subject?, title?, author?, section?, stylesheet?, registerFont?, slide*)+>
<!ATTLIST presentation
  filename CDATA #REQUIRED
  pageDuration CDATA #IMPLIED
  pageWidth CDATA #IMPLIED
  pageHeight CDATA #IMPLIED
>
<!-- First-Level Elements -->
<!ELEMENT author (#PCDATA)>
<!-- PDF Document Info -->
<!ELEMENT section (fixedimage*, rectangle*, roundrect*, ellipse*, polygon*, line*, string*, infostring*, customshape*, slide*)+>
<!ATTLIST section
  name CDATA #REQUIRED
>
<!ELEMENT slide (fixedimage*, rectangle*, roundrect*, ellipse*, polygon*, line*, string*, infostring*, customshape*, frame*, notes*)+>
<!ATTLIST slide
  id CDATA #REQUIRED
  title CDATA #REQUIRED
  outlineentry CDATA #IMPLIED
  outlinelevel NMTOKEN #IMPLIED
  showIDName (%bool;) "true"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT stylesheet EMPTY>
<!ATTLIST stylesheet
  path CDATA #IMPLIED
  module CDATA #REQUIRED
  function CDATA #REQUIRED
>
<!ELEMENT registerFont EMPTY>
<!ATTLIST registerFont
  name CDATA #REQUIRED
  path CDATA #REQUIRED
>
<!ELEMENT subject (#PCDATA)>
<!-- PDF Document Info -->
<!ELEMENT title (#PCDATA)>
<!-- PDF Document Info -->
<!-- Other elements -->
<!ELEMENT b (#PCDATA)>
<!ELEMENT customshape EMPTY>
<!ATTLIST customshape
  path CDATA #IMPLIED
  module CDATA #IMPLIED
  class CDATA #IMPLIED
  initargs CDATA #IMPLIED
  align (%align.values;) #IMPLIED
>
<!ELEMENT ellipse EMPTY>
<!ATTLIST ellipse
  x1 NMTOKEN #REQUIRED
  y1 NMTOKEN #REQUIRED
  x2 NMTOKEN #REQUIRED
  y2 NMTOKEN #REQUIRED
  fill CDATA #IMPLIED
  stroke CDATA "(0,0,0)"
  linewidth NMTOKEN "0"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT fixedimage EMPTY>
<!ATTLIST fixedimage
  filename CDATA #REQUIRED
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  width NMTOKEN #IMPLIED
  height NMTOKEN #IMPLIED
>
<!ELEMENT font (#PCDATA)>
<!ATTLIST font
  name CDATA #IMPLIED
  color CDATA #IMPLIED
  size NMTOKEN #IMPLIED
>
<!ELEMENT frame (para*, prefmt*, pycode*, image*, table*, fixedimage*, rectangle*, roundrect*, ellipse*, polygon*, line*, string*, customshape*, spacer*, drawing*, pageCatcherFigure*)+>
<!ATTLIST frame
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  width NMTOKEN #REQUIRED
  height NMTOKEN #REQUIRED
  leftmargin NMTOKEN "0"
  rightmargin NMTOKEN "0"
  topmargin NMTOKEN "0"
  bottommargin NMTOKEN "0"
  border (%bool;) "false"
>
<!ELEMENT greek (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT image EMPTY>
<!ATTLIST image
  filename CDATA #REQUIRED
  width NMTOKEN #IMPLIED
  height NMTOKEN #IMPLIED
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT infostring (#PCDATA)>
<!ATTLIST infostring
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  color CDATA "(0,0,0)"
  font CDATA "Times-Roman"
  size NMTOKEN "12"
  align (%align.values;) "left"
>
<!ELEMENT line EMPTY>
<!ATTLIST line
  x1 NMTOKEN #REQUIRED
  y1 NMTOKEN #REQUIRED
  x2 NMTOKEN #REQUIRED
  y2 NMTOKEN #REQUIRED
  stroke CDATA "(0,0,0)"
  width NMTOKEN "0"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT notes (para+)>
<!ELEMENT para (#PCDATA | i | b | u | super | sub | font | greek)*>
<!ATTLIST para
  style CDATA "Normal"
  bullettext CDATA #IMPLIED
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT polygon EMPTY>
<!ATTLIST polygon
  points CDATA #REQUIRED
  fill CDATA #REQUIRED
  stroke CDATA "(0,0,0)"
  linewidth NMTOKEN "0"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT prefmt (#PCDATA)>
<!ATTLIST prefmt
  xml:space (default | preserve) #FIXED "preserve"
  style CDATA #IMPLIED
>
<!ELEMENT pycode (#PCDATA)>
<!ATTLIST pycode
  xml:space (default | preserve) #FIXED "preserve"
  style CDATA #IMPLIED
>
<!ELEMENT rectangle EMPTY>
<!ATTLIST rectangle
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  width NMTOKEN #REQUIRED
  height NMTOKEN #REQUIRED
  fill CDATA #IMPLIED
  stroke CDATA "(0,0,0)"
  linewidth NMTOKEN "0"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT roundrect EMPTY>
<!ATTLIST roundrect
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  width NMTOKEN #REQUIRED
  height NMTOKEN #REQUIRED
  fill CDATA #IMPLIED
  stroke CDATA "(0,0,0)"
  linewidth NMTOKEN "0"
  radius NMTOKEN "6"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT spacer EMPTY>
<!ATTLIST spacer
  height NMTOKEN #REQUIRED
>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string
  x NMTOKEN #REQUIRED
  y NMTOKEN #REQUIRED
  color CDATA "(0,0,0)"
  font CDATA "Times-Roman"
  size NMTOKEN "12"
  align (%align.values;) "left"
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT super (#PCDATA)>
<!ELEMENT table (#PCDATA)>
<!ATTLIST table
  xml:space (default | preserve) #FIXED "preserve"
  widths CDATA #IMPLIED
  heights CDATA #IMPLIED
  style CDATA #IMPLIED
  colDelim CDATA #IMPLIED
  rowDelim CDATA #IMPLIED
  effectname (%effectname.values;) #IMPLIED
  effectdirection (%effectdirection.values;) "0"
  effectdimension (%effectdimension.values;) "H"
  effectmotion (%effectmotion.values;) "I"
  effectduration NMTOKEN "1"
>
<!ELEMENT u (#PCDATA)>
<!ELEMENT drawing EMPTY>
<!ATTLIST drawing
  module CDATA #REQUIRED
  constructor CDATA #REQUIRED
  baseDir CDATA #IMPLIED
  hAlign CDATA #IMPLIED
  showBoundary CDATA #IMPLIED
>
<!ELEMENT pageCatcherFigure (#PCDATA)>
<!ATTLIST pageCatcherFigure
  filename CDATA #REQUIRED
  pageNo CDATA #REQUIRED
  caption CDATA #IMPLIED
  width CDATA #IMPLIED
  height CDATA #IMPLIED
  background CDATA #IMPLIED
  border CDATA #IMPLIED
  scaleFactor CDATA #IMPLIED
>

=== csterryliu/Legal-Attest-Letter-Generator-TW-Django/lal_web/lal_web/generator/lal_module/dep/reportlab/tools/pythonpoint/demos/htu.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE presentation SYSTEM "../pythonpoint.dtd">
<presentation filename="htu.pdf">
  <stylesheet module="htu" function="getParagraphStyles"/>
  <section name="Main">
    <rectangle x="20" width="96" y="20" height="555" fill="ReportLabBlue"/>
    <infostring size="14" align="right" x="800" y="36">
        &#169; 2002, H. Turgut UYAR
    </infostring>
    <slide title="New Features" id="Slide000">
      <frame x="120" y="72" width="700" height="418" leftmargin="36" rightmargin="36">
        <image filename="pplogo.gif" width="200" height="150"/>
        <spacer height="30"/>
        <para style="Title">New features in PythonPoint</para>
        <para style="Author">H. Turgut Uyar</para>
        <para style="EMail">uyar@cs.itu.edu.tr</para>
      </frame>
    </slide>
    <slide title="TrueType Support" id="Slide002">
      <frame x="120" y="515" width="700" height="60" leftmargin="36" rightmargin="36">
        <para style="Heading1">TrueType Support</para>
      </frame>
      <frame x="120" y="72" width="700" height="418" leftmargin="36" rightmargin="36">
        <para>PythonPoint can read UTF-8 encoded input files and produce
            correct output (provided your font has all necessary
            characters). That enables you, for example, to have native (in my
            case, Turkish) characters in your document:</para>
        <para style="Indent">
          <!--  if you have any trouble with these, execute the lines below
            to find out what we really intended 
            >>> turkishChars =  u"\u011e \u011f \u0130 \u0131 \u015e \u015f"
            >>> print turkishChars
            >>> print turkishChars.encode("utf-8")
            þ ø İ ı ľ ĸ
            >>> 
            -->
          <font name="Serif" size="32"> 0 ^  1 _</font>
        </para>
      </frame>
    </slide>
    <slide title="Effects" id="Slide003">
      <frame x="120" y="515" width="700" height="60" leftmargin="36" rightmargin="36">
        <para style="Heading1">Effects</para>
      </frame>
      <frame x="120" y="72" width="700" height="418" leftmargin="36" rightmargin="36">
        <para>Paragraphs, images, tables and geometric shapes can now have
            effectname, effectdirection, effectdimension, effectmotion and
            effectduration attributes:</para>
        <para style="Indent" effectname="Dissolve">A paragraph</para>
        <image filename="pplogo.gif" width="80" height="60" effectname="Box"/>
        <table style="table1" effectname="Split">
            Col1,Col2,Col3
            Row1Col1,Row1Col2,Row1Col3
            Row2Col1,Row2Col2,Row2Col3
        </table>
      </frame>
      <roundrect x="180" y="150" width="110" height="50" radius="15" fill="(0,1,0)" effectname="Glitter"/>
      <string font="Helvetica" size="32" x="200" y="165" align="left" color="(1,0,0)" effectname="Blinds">String</string>
      <line x1="248" y1="84" x2="520" y2="84" stroke="(1,0,1)" effectname="Wipe"/>
    </slide>
    <slide title="Printing" id="Slide004" outlinelevel="1">
      <frame x="120" y="515" width="700" height="60" leftmargin="36" rightmargin="36">
        <para style="Heading1">Printing</para>
      </frame>
      <frame x="120" y="72" width="700" height="418" leftmargin="36" rightmargin="36">
        <para>Be careful when using effects: A new slide is created for
            each effect, so DON'T print the resulting PDF file.</para>
        <para effectname="Box">new command-line option: --printout</para>
        <para style="Indent">produces printable PDF</para>
      </frame>
    </slide>
    <slide title="New Paragraph Styles" id="Slide005">
      <frame x="120" y="515" width="700" height="60" leftmargin="36" rightmargin="36">
        <para style="Heading1">New Paragraph Styles</para>
      </frame>
      <frame x="120" y="72" width="700" height="418" leftmargin="36" rightmargin="36">
        <para style="Bullet">Bullet2 - Second level bullets</para>
        <para style="Bullet2">Here's an example</para>
        <para style="Bullet2">Or an example with a longer text to see
            how it wraps at the end of each line</para>
        <para style="Bullet">Author and EMail</para>
        <para style="Bullet2">See the cover page for examples</para>
        <para style="Bullet">They have to be in the style file, so either use
            the htu style file or edit your style file</para>
      </frame>
    </slide>
    <slide title="ToDo" id="Slide006">
      <frame x="120" y="515" width="700" height="60" leftmargin="36" rightmargin="36">
        <para style="Heading1">ToDo</para>
      </frame>
      <frame x="120" y="72" width="700" height="418" leftmargin="36" rightmargin="36">
        <para style="Bullet">Unicode chars in the outline</para>
      </frame>
    </slide>
  </section>
</presentation>

=== csterryliu/Legal-Attest-Letter-Generator-TW-Django/lal_web/lal_web/generator/lal_module/dep/reportlab/tools/pythonpoint/demos/figures.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Andy Robinson (ReportLab Europe Ltd.) -->
<!DOCTYPE presentation SYSTEM "../pythonpoint.dtd">
<presentation filename="figures.xml" pageDuration="10">
  <stylesheet module="standard" function="getParagraphStyles"/>
  <title>New Feature Tests</title>
  <author>
        Andy Robinson
    </author>
  <subject>
        Reportlab Sample Applications
    </subject>
  <section name="Main">
    <!-- any graphics in the section go on all its pages as a backdrop -->
    <rectangle height="555" fill="ReportLabBlue" x="20" width="96" y="20"/>
    <!--fixedimage height="64" filename="leftlogo.gif" x="20" width="96" y="510"/-->
    <customshape module="customshapes" class="Logo" initargs="(20,510,96,64)"/>
    <!--infostring size="14" align="right" x="800" y="36">
            &#187;%(title)s, page %(page)s&#171;
        </infostring-->
    <!-- Now for the slides -->
    <slide title="Introduction" id="Slide001" effectname="Box" effectduration="2">
      <frame height="468" x="120" y="72" rightmargin="36" width="700" leftmargin="36">
        <para style="Heading1">
                    New Feature Test Cases - Figures, Drawings and Included Pages
                </para>
        <para style="BodyText">
                    especially images and pagecatcher stuff...
                </para>
        <para style="BodyText">
          <i>
                        PythonPoint
                    </i>
                    lets you create attractive and consistent presentation slides
                on any platform.  It is a demo app built on top of the PDFgen PDF library
                and the PLATYPUS Page Layout library.  Essentially, it converts slides
                in an XML format to PDF.
                </para>
        <para style="BodyText">
                    It can be used right now to create slide shows, but will
                    undoubtedly change and evolve.  Read on for a tutorial...
                </para>
      </frame>
    </slide>
    <slide title="Test Drawing Tag" id="Slide002" effectname="Dissolve" effectduration="2">
      <frame height="468" x="120" y="72" rightmargin="36" width="700" leftmargin="36" border="true">
        <para style="Heading1">
                    Drawing Tag In Action within story context
                </para>
        <para style="BodyText">
                    especially images and pagecatcher stuff...
                </para>
        <para style="BodyText">Hope that came out right-aligned with a box around it...</para>
        <drawing module="slidebox" constructor="SlideBoxDrawing" showBoundary="1" hAlign="CENTER"/>
      </frame>
    </slide>
    <slide title="Test PageFigure Tag" id="Slide002" effectname="Glitter" effectduration="2">
      <frame height="468" x="120" y="72" rightmargin="36" width="300" leftmargin="36" border="true">
        <para style="Heading1">PageFigure</para>
        <para style="BodyText">This imports a page and displays it.  Since this will typically be used to show
        A4/Letter pages, it does a 'shrink to fit' based on frame width.  The scaleFactor attribute can override this,
        as I did below...
        </para>
        <pageCatcherFigure filename="../../../../rlextra/pageCatcher/test/ir684.pdf" pageNo="0" caption="IR684 - Authorizing your Agent" scaleFactor="0.1"/>
      </frame>
      <frame height="468" x="450" y="72" width="325" border="true">
        <pageCatcherFigure filename="../../../rlextra/pageCatcher/test/ir684.pdf" pageNo="0" caption="IR684 - Authorizing your Agent"/>
      </frame>
    </slide>
  </section>
</presentation>
